@startuml 1

' ####################
' ### Ядро системы ###
' ####################

class Театр {
  + название: String
  + адрес: String
}

class Зал {
  + номер: int
  + списокМест: List<Место>
  + показатьСвободныеМеста(): List<Место>
}

class Спектакль {
  + название: String
  + датаВремя: DateTime
  + зал: Зал
  + ценаБазовая: double
}

class Место {
  + ряд: int
  + номер: int
  + статус: String {свободно, забронировано}
  + категория: String
  + рассчитатьЦену(Спектакль): double
}

' ########################
' ### Работа с клиентом ###
' ########################

class Покупатель {
  + имя: String
  + email: String
}

class Билет {
  + id: String
  + статус: String
  + оплатить(): void
  + отменить(): void
}

class Корзина {
  + списокБилетов: List<Билет>
  + итоговаяЦена: double
  + применитьСкидку(код: String): void
}

' #########################
' ### Внешние компоненты ###
' #########################

class "Интерфейс (UI)" as UI {
  + показатьРасписание(): List<Спектакль>
  + выбратьМесто(Спектакль, Место): Билет
  + открытьКорзину(): Корзина
  + ввестиДанныеПокупателя(): Покупатель
  + подтвердитьОплату(Корзина): boolean
}

class "Платежная система" as Payment {
  + провестиОплату(Билет): boolean
}

' ####################
' ### Связи между классами ###
' ####################

Театр "1" *-- "1..*" Зал: Содержит
Зал "1" *-- "1..*" Место: Содержит
Спектакль "1" --> "1" Зал: Указывает на

Билет "1" --> "1" Место: Указывает на
Билет "1" --> "1" Спектакль: Указывает на

Корзина "1" o-- "1..*" Билет: Состоит из

UI "1"-->"1" Покупатель : Создает/обновляет
UI "1"-->"1..*" Спектакль : Запрашивает расписание
UI "1"-->"1..*" Зал : Получает схему мест
UI "1"-->"1" Корзина : Управляет билетами
UI "1"-->"1" Payment : Инициирует оплату
Payment "1"-->"1" Билет : Обновляет статус

@enduml