@startuml
left to right direction

'#######################
'### Нормативно-справочные сущности (НСИ)
'#######################

entity Справочник_работ {
  *Код_работы
  Название_работы
  Стандартная_стоимость
  Норма_времени
}

entity Справочник_запчастей {
  *Код_запчасти
  Название
  Цена
  Остаток_на_складе
  Минимальный_запас
}

entity Типы_неисправностей {
  *Код_неисправности
  Описание
  Критичность
}

entity Статусы_заказа {
  *Код_статуса
  Название_статуса
}

'#######################
'### Базовые сущности
'#######################

entity Клиент {
  *ИД_клиента
  ФИО
  Телефон
  Email
  Дата_регистрации
}

entity Велосипед {
  *ИД_велосипеда
  ИД_клиента
  Марка
  Модель
  Год_выпуска
  VIN
}

entity Заявка {
  *ИД_заявки
  ИД_клиента
  ИД_велосипеда
  Дата_заявки
  Описание_проблемы
  Код_статуса
}

entity Заказ {
  *ИД_заказа
  ИД_заявки
  ИД_менеджера
  ИД_механика
  Дата_начала
  Дата_окончания
}

entity Акт_работ {
  *ИД_акта
  ИД_заказа
  Дата_проверки
  Результат
  Подпись_механика
}

entity Смета {
  *ИД_сметы
  ИД_заказа
  Стоимость_работ
  Стоимость_запчастей
  Итоговая_сумма
  Подтверждение_клиента
}

entity Оплата {
  *ИД_оплаты
  ИД_заказа
  Сумма
  Дата_оплаты
  Способ_оплаты
}

entity Менеджер {
  *ИД_менеджера
  ФИО
  Контактные_данные
}

entity Механик {
  *ИД_механика
  ФИО
  Квалификация
}

'#######################
'### Связи
'#######################

Клиент "1" -- "n" Велосипед
Клиент "1" -- "n" Заявка
Велосипед "1" -- "n" Заявка

Заявка "1" -- "1" Заказ
Заявка "1" -- "1" Менеджер
Типы_неисправностей "n" -- "1" Заявка

Менеджер "1" -- "n" Заказ
Механик "1" -- "n" Заказ
Механик "1" -- "n" Акт_работ
Велосипед "n" -- "1" Механик

Заказ "1" -- "n" Справочник_работ
Заказ "1" -- "n" Справочник_запчастей
Заказ "1" -- "1" Смета
Клиент "1" -- "1" Оплата
Заказ "1" -- "n" Акт_работ

Справочник_работ "n" -- "n" Справочник_запчастей : Требует

Смета "1" -- "1" Оплата : Подтверждает
Статусы_заказа "1" -- "n" Заказ

@enduml