@startuml

' Основные классы
class Билет
class Спектакль
class Покупатель
class Дата
class Время
class Цена
class Место
class Зал
class Театр

' Дополнительные классы
class КатегорияМеста
class Скидка
class Расписание
class Актер
class Режиссер

' Связи между классами
Билет --> Спектакль
Билет --*  Место
Билет *-- Покупатель
Билет *-- Цена
Цена --> Скидка
Театр *-- Зал
Зал *-- Место
Место --> КатегорияМеста
Спектакль --o Расписание
Спектакль --> Зал
Расписание *-- Дата
Расписание *-- Время
Расписание o-- Актер
Расписание o-- Режиссер

@enduml